config/routes.rb
Rails.application.routes.draw do
   
   
  devise_for :users
    resources :parkings
   root "parkings#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord
  
   validates_presence_of :parking_type, :plate, :start_at
   validates_inclusion_of :parking_type, :in => ["guest", "short-term", "long-term"]
   belongs_to :user, :optional => true
   
   def validate_end_at_with_amount
     if ( end_at.present? && amount.blank? )
       errors.add(:amount, "有结束时间就必须有金额")
     end
 
     if ( end_at.blank? && amount.present? )
       errors.add(:end_at, "有金额就必须有结束时间")
     end
   end
   
     # 计算停了多少分钟
     def duration
       ( end_at - start_at ) / 60
     end

  def calculate_amount
    
      if self.parking_type == "guest"
        self.amount = calculate_guest_term_amount  # 一般费率
      elsif self.parking_type == "long-term"
          self.amount = calculate_long_term_amount # 长期费率
      elsif self.parking_type == "short-term"
        self.amount = calculate_short_term_amount  # 短期费率
      end
  end


  def calculate_guest_term_amount
    if duration <= 60
      self.amount = 200
    else
      self.amount = 200 + ((duration - 60).to_f / 30).ceil * 100
    end
  end

  def calculate_short_term_amount
    if duration <= 60
      self.amount = 200
    else
      self.amount = 200 + ((duration - 60).to_f / 30).ceil * 50
    end
  end

  def calculate_long_term_amount
    if duration <= 1440
      self.amount = 2000
    else
      self.amount = 2000 + ((duration - 1440 ).to_f / 1440).ceil * 1000
    end 
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :parkings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
   before_action :authenticate_user! 
    # Step1: 显示开始停车的表单
    def index
    #  @parkings = Parking.order("id DESC").all
      @parkings = Parking.order("id DESC").all.paginate(:page => params[:page], :per_page => 10)
    end 
    
    
    def new
      @parking = Parking.new
    end
 
    # Step2: 新建一笔停车，纪录下开始时间
    def create
      @parking = Parking.new(:start_at => Time.now)
      @parking.parking_type = params[:parking][:parking_type]
      @parking.plate = params[:parking][:plate]
      @parking.user = current_user
    
      if @parking.save
 
        redirect_to parking_path(@parking)
      else 
        render :new
      end 
    end
 
    # Step3: 如果还没结束，显示结束停车的表单
    # Step5: 如果已经结束，显示停车费用。
    def show
      @parking = Parking.find(params[:id])
    end
 
 # Step4: 结束一笔停车，记录下结束时间，并且计算停车费
    def update
      @parking = Parking.find(params[:id])
      @parking.end_at = Time.now
      @parking.calculate_amount
 
      @parking.save!
 
      redirect_to parking_path(@parking)
    end
    
    def destroy 

     @parking = Parking.find(params[:id])
     @parking.destroy
     flash[:alert] = " Deleted "
     redirect_to parkings_path

    end 
    # private 
    # def parking_params
    #   params.require(:parking).permit(:parking_type => "guest", :plate =>"" , :start_at => Time.now)
    # end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Rails for Parking
        <br>Design by
        <a href="https://www.linkedin.com/in/finn-wang-870b67185/" target=_new>Fei Wang</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/parkings">Parking List</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav center">
               
                   
                <% if !current_user %>
                   <li><%= link_to("Sign up", new_user_registration_path) %> </li>
                   <li><%= link_to("Login", new_user_session_path) %></li>
                 <% else %>
                   <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                         Hi!, <%= current_user.email %>
                         <b class="caret"></b>
                     </a>
                     <ul class="dropdown-menu">
                         <li> <%= link_to("Log out", destroy_user_session_path, method: :delete) %> </li>
                         <li><%= link_to('Change Password', edit_registration_path(:user)) %></li>
                     </ul>
                   </li>
                 <% end %>


                 </ul>

                
            

        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Parking101</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/parkings/index.html.erb
                 
               <ul class="nav navbar-nav navbar-center">   
               <li>
                <b> Find the vehicle from current page:</b>
               </li>
                <li>
                <input class="form-control mr-sm-2 navbar-right" id="myInput" type="text" placeholder="Search" aria-label="Search">
                </li>
                <!-- <li>-->
                <!--<button class="btn btn-outline-success my-2 my-sm-0 navbar-right" type="submit">Search</button>-->
                <!--</li>-->
                </ul>

<div class="col-md-12">
  <div class="group">
    <%= link_to("New parking", new_parking_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>Starting Time</td>
        <td>License Plates</td>
        <td>Parking Type</td>
        <td>Amount $</td>
        <td>Status</td>
      </tr>
    </thead>
    <tbody id="myTable">
      <% @parkings.each do |park| %>
        <tr>
          <td><%= park.start_at %></td>
          <td><%= link_to(park.plate, parking_path(park)) %></td>
          <td><%= park.parking_type %></td>
          <td>
          <% if park.amount.to_f != 0 %>
          <%= park.amount.to_f / 100 %>
          <% else %>
           Continuing
           <% end %>
          </td>
          
          <td>
          
              <%= link_to("Already Paid --Delete", parking_path(park),    class: "btn btn-sm btn-default", 
                          method: :delete, data: { confirm: "Are you sure? Is it paid ? " } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
     <div class="text-center">
       <%= will_paginate @parkings %>
     </div>

</div>


<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>

app/views/parkings/new.html.erb
<div class="center jumbotron text-center">
   <h1>Calculator for Parking Fee</h1>
  
   <hr>
   <%= form_for @parking do |f| %>

    <% if @parking.errors.any? %>
    <ul style="background-color:Tomato;">
      <% @parking.errors.full_messages.each do |msg| %>
    
        <li><%= msg %></li>
      <% end %>
    </ul>
    <% end %>

  
    Start at : <%= Time.now %>
    <br>
  
    Plate No.:  <%= f.text_field :plate, placeholder: "Plate No"%>
    

   
     <label>
       <%= f.radio_button :parking_type, "guest", :checked => "checked" %> Guest 
     </label>
 
     <label>
       <%= f.radio_button :parking_type, "short-term" %> Short-term
     </label>
 
     <label>
       <%= f.radio_button :parking_type, "long-term" %> Long-term
     </label>
 
     <p><%= f.submit "Start to count" %> | <a id="my-click">   Price List </a>  </p>

  <% end %>

  <div id="foo" style="border: 1px solid red;">
    <a id="my-hide-click">Hide</a>
    <p> As a Guest: $ 2 / hour </p>
  
    <p> As a Member: short-term (less than 24 hours) $ 2 / hour for the first hour then $ 1 / hour </p>
  
    <p> and long-term (more than 1 day) is $ 20 for the first day then $ 10 / day <p>
    
  </div>
  <%= link_to image_tag("parking-sign.jpg", alt: "parking sign", size: "500x350"  ) %> 
  <%= link_to image_tag("DC.jpg", alt: "DC parking sign", size: "500x350" ) %> 

</div>



<script>
  $("#foo").hide();

  $("#my-click").click(function(){
    $("#foo").show();
  })

  $("#my-hide-click").click(function(){
    $("#foo").hide();
  })
</script>

app/views/parkings/show.html.erb
<h1>Calculator for Parking Fee</h1>

<% if @parking.amount.present? # 已经结束，显示停车费 %>


  <div class="col s12 m7  text-center">
    <h2 class="header">Vehicle registration plate: <%= @parking.plate %></h2>
    <div class="card horizontal">
      <div class="card-image">
        <%= link_to image_tag("cherry-blossom.jpg", alt: "parking sign", size: "450x230"  ) %>
      </div>
      <div class="card-stacked">
        <div class="card-content">
            <p></p>
            <h3>Parking Type: <%= @parking.parking_type %></h3>
            
            <p>From <%= @parking.start_at %> To <%= @parking.end_at %><p>
            <p>It's <%= @parking.duration %> min</p>
            <h4>Have to pay <%= number_to_currency(@parking.amount.to_f / 100, :unit => "$") %> Dollar</h4>
          
            <p><%= link_to "A New Parking", new_parking_path %> | <%= link_to "Return", parkings_path %></p>
        </div>
        <div class="card-action">
          <a href="https://www.google.com/maps">This is a map</a>
        </div>
      </div>
    </div>
  </div>
           
           

<% else # 还没结束，显示结束按钮 %>
<%= form_for @parking do |f| %>

   <div class="card text-center">
      <div class="card-header">
        WELCOME
      </div>
      <div class="card-body">
         <%= link_to image_tag("car-plates", alt: "parking sign", size: "100x100"  ) %>
        <h1 class="card-title" > Vehicle Plate: <%=  @parking.plate %>  </h1>
        <p class="card-text">Thank you for choosing us</p>
        <p><%= f.submit "Stop Parking" %>  </p>
        <a href="/parkings" class="btn btn-primary">Return to List</a>
      </div>
      <div class="card-footer text-muted">
        
      </div>
    </div>

  <% end %>

<% end %>

app/views/welcome/index.html.erb
<h1>Hello world</h1>